travis:
  secure:
    BINSTAR_TOKEN: Jti9Mag+JNyHCAvqVxpBhlHzp5lF8Y9cBFRgLqU1AfjyJoLpyherui4WAGJW7TPWR3jax1w1q5yje2vwmF+5CbgS2cW1mQUQuD20djhXfIwnddWlR3DbECOUtE7dA7fC9occrtnGjJkp9h4A++VwTW7aU/UXVtjXsWQuUfFQ2/jw3PoZLkaaGnFuhnQ6Qr9hZlnDTBAjpeTn/94QlxT72EBQld1d7BnN1pbX2A3gt2Ha42n/ofrf0ca7fxS1Gx4aEd/hO4WZ4weG5EKaaxn4+5rHv3qgQ52kSgyJU9EzhFvYCUPyDWOQ52vdfWpRHBvCsFZHQW4hqmZET/r9RFS7uaQfT+MYaZa9e11byAaj5V0Mn9VXLSPQ+9a/XD+0lATysHviik+zkjfbDeCLTRZCKKu4VGxJSJYVSMPsnHsaVLvXav5Ojob9HXc4C2rSFAI+moq7HIs5pmlZ6tHRwbUHQ7SYDl930QlAC2wCtTtyo+cS4JFby+86GQdHJ8gDiCOtY7fvKakUDtPcumAcSoRdwtdjwIiME7WKa3lIKAOwLHgOUodd7bHCUPzsvgOu0lOrHHxBoFnyDJV+e7RJalWKrzpUvdEJYzXzuXK3wuURhzKe1iaAdB3CAcCaJjYZ2Di8PvIyHyg7mAMKmKNoKHIwUVvfc6QZNjhyJW/7JmcbspI=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
